# Copyright 2015 OpenStack Foundation
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

"""add_portuse_status

Revision ID: 1963b9d4f438
Revises: 15f5cfd55b28
Create Date: 2015-08-27 16:13:54.665945

"""

# revision identifiers, used by Alembic.
revision = '1963b9d4f438'
down_revision = '15f5cfd55b28'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ports",
         sa.Column('used_status',sa.String(length=10), nullable=True)
    )


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        "ports",
        'used_status')
