# Copyright 2016 OpenStack Foundation
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

"""change for 'mulity_ha_network_one_tenant

Revision ID: 225971f74453
Revises: feaf26edca9
Create Date: 2016-03-03 15:47:07.137710

"""

# revision identifiers, used by Alembic.
revision = '225971f74453'
down_revision = '50d61f6e625e'


from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'ha_router_networks_for_gcloud',
        sa.Column('tenant_id', sa.String(255), nullable=False),
        sa.Column('network_id', sa.String(36),sa.ForeignKey('networks.id', ondelete="CASCADE"),
                           nullable=False, primary_key=True))
    op.create_table(
        'router_ha_network_info',
        sa.Column('router_id', sa.String(255),sa.ForeignKey('routers.id', ondelete="CASCADE"), primary_key=True,
                          nullable=False),
        sa.Column('network_id', sa.String(36),
                           sa.ForeignKey('networks.id', ondelete="CASCADE"),
                           nullable=False, primary_key=True)
    )

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ha_router_networks_for_gcloud')
    op.drop_table('router_ha_network_info')
    ### end Alembic commands ###
