# Copyright 2015 OpenStack Foundation
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

"""add_networks_createtime

Revision ID: 3148b4afb520
Revises: 4f78f33d0d1e
Create Date: 2015-05-18 14:22:57.273760

"""

# revision identifiers, used by Alembic.
revision = '3148b4afb520'
down_revision = '4f78f33d0d1e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "networks",
         sa.Column('create_time', sa.String(length=26), nullable=False)
    )
    op.add_column(
        "networks",
         sa.Column('user_id', sa.String(length=64), nullable=False)
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        "networks",
        'create_time')
    op.drop_column(
        "networks",
        'user_id')
    ### end Alembic commands ###
