# Copyright 2015 OpenStack Foundation
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

"""add_gcloud_nats_table

Revision ID: 411dbb33848a
Revises: 2806f2233aca
Create Date: 2015-12-08 10:20:21.172927

"""

# revision identifiers, used by Alembic.
revision = '411dbb33848a'
down_revision = '2806f2233aca'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gcloudnats',
    sa.Column('tenant_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('router_id', sa.String(length=36), nullable=False),
    sa.Column('port_id', sa.String(length=36), nullable=False),
    sa.Column('gw_port_id', sa.String(length=36), nullable=False),
    sa.Column('ext_ip', sa.String(length=64), nullable=True),
    sa.Column('int_ip', sa.String(length=64), nullable=True),
    sa.Column('ext_port', sa.Integer(), nullable=True),
    sa.Column('int_port', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.String(length=26), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['router_id'], ['routers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gw_port_id'], ['ports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gcloudnats')
    ### end Alembic commands ###
