# Copyright 2015 OpenStack Foundation
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

"""alter_subnets

Revision ID: 42662df97563
Revises: 3148b4afb520
Create Date: 2015-05-18 16:21:01.872739

"""

# revision identifiers, used by Alembic.
revision = '42662df97563'
down_revision = '3148b4afb520'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subnets",
         sa.Column('create_time', sa.String(length=26), nullable=False)
    )
    op.add_column(
        "subnets",
         sa.Column('user_id', sa.String(length=64), nullable=False)
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        "subnets",
        'create_time')
    op.drop_column(
        "subnets",
        'user_id')
    ### end Alembic commands ###
