# Copyright 2015 OpenStack Foundation
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

"""add_subnet_type

Revision ID: 508c1687a065
Revises: 411dbb33848a
Create Date: 2015-12-08 11:07:28.344940

"""

# revision identifiers, used by Alembic.
revision = '508c1687a065'
down_revision = '411dbb33848a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subnets', sa.Column('type', sa.String(length=32), nullable=True))


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subnets', 'type')
    ### end Alembic commands ###
