# Copyright 2015 OpenStack Foundation
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

"""alter_gloud_nats_vif

Revision ID: 5788e5ba29bf
Revises: 508c1687a065
Create Date: 2015-12-13 14:35:32.960066

"""

# revision identifiers, used by Alembic.
revision = '5788e5ba29bf'
down_revision = '508c1687a065'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gcloudnats",
         sa.Column('vif_subnet_cidr', sa.String(length=64), nullable=True)
    )
    op.add_column(
        "gcloudnats",
         sa.Column('vif_subnet_gateway', sa.String(length=64), nullable=True)
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        "gcloudnats",
        'vif_subnet_cidr')
    op.drop_column(
        "gcloudnats",
        'vif_subnet_gateway')
    ### end Alembic commands ###
