# Copyright 2015 OpenStack Foundation
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

"""alter_securitygroup_table

Revision ID: 58b6fc185866
Revises: 152dea1319d8
Create Date: 2015-05-21 10:54:21.115190

"""

# revision identifiers, used by Alembic.
revision = '58b6fc185866'
down_revision = '152dea1319d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
     
    op.add_column(
        "securitygroups",
         sa.Column('create_time',sa.String(length=26), nullable=False)
    )
    op.add_column(
        "securitygroups",
         sa.Column('user_id',sa.String(length=64), nullable=False)
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
      
    ### end Alembic commands ###
    op.drop_column(
        "securitygroups",
        'create_time')
    op.drop_column(
        "securitygroups",
        'user_id')
