# Copyright 2015 OpenStack Foundation
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

"""alter_lb_members_gcloud

Revision ID: a71fbeac4ed
Revises: 4a7422ca77b2
Create Date: 2015-05-27 10:34:23.129349

"""

# revision identifiers, used by Alembic.
revision = 'a71fbeac4ed'
down_revision = '4a7422ca77b2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "members",
         sa.Column('port_id',sa.String(length=36), nullable=True)
    )
    op.add_column(
        "members",
         sa.Column('instance_id',sa.String(length=36), nullable=True)
    )
    op.add_column(
        "members",
         sa.Column('create_time',sa.String(length=26), nullable=True)
    )
    op.add_column(
        "members",
         sa.Column('user_id',sa.String(length=64), nullable=True)
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        "members",
        'port_id')
    op.drop_column(
        "members",
        'instance_id')
    op.drop_column(
        "members",
        'create_time')
    op.drop_column(
        "members",
        'user_id')
    ### end Alembic commands ###
