# Copyright 2015 OpenStack Foundation
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

"""add_gcloud_nats_plus_table

Revision ID: feaf26edca9
Revises: 5788e5ba29bf
Create Date: 2015-12-13 14:45:27.305616

"""

# revision identifiers, used by Alembic.
revision = 'feaf26edca9'
down_revision = '5788e5ba29bf'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gcloudnatpluss',
    #sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('router_id', sa.String(length=36), nullable=False),
    sa.Column('network_id', sa.String(length=36), nullable=True),
    sa.Column('subnet_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['router_id'], ['routers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('router_id'),
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gcloudnatpluss')
    ### end Alembic commands ###
